"""initial claims table

Revision ID: 1976c68bb59e
Revises: 
Create Date: 2026-02-25 00:38:08.192430

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1976c68bb59e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('claims',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('member_id', sa.String(length=50), nullable=False),
    sa.Column('provider_id', sa.String(length=50), nullable=False),
    sa.Column('diagnosis_code', sa.String(length=20), nullable=False),
    sa.Column('procedure_code', sa.String(length=20), nullable=False),
    sa.Column('claim_amount', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('fraud_flag', sa.Boolean(), nullable=False),
    sa.Column('approved_amount', sa.Float(), nullable=False),
    sa.Column('rejection_reasons', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_claims_member_id'), 'claims', ['member_id'], unique=False)
    op.create_index(op.f('ix_claims_provider_id'), 'claims', ['provider_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_claims_provider_id'), table_name='claims')
    op.drop_index(op.f('ix_claims_member_id'), table_name='claims')
    op.drop_table('claims')
    # ### end Alembic commands ###
